# Generated by Django 5.1.2 on 2024-11-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_roomrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
    ]
