# Generated by Django 5.1.2 on 2024-11-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_room_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='room_name',
        ),
    ]
